apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tech-challenge-app.fullname" . }}
  labels:
    {{- include "tech-challenge-app.labels" . | nindent 4 }}
data:
  db_name: {{ .Values.configmap.db_name }}
  db_port: {{ .Values.configmap.db_port | quote }}
  db_host: {{ .Values.configmap.db_host }}
  listen_host: {{ .Values.configmap.listen_host }}
