apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tech-challenge-app.fullname" . }}
  labels:
    {{- include "tech-challenge-app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "tech-challenge-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tech-challenge-app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tech-challenge-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          args: ['serve']
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: VTT_DBUSER
              valueFrom:
                secretKeyRef:
                    name:  {{ include "tech-challenge-app.fullname" . }}
                    key: db_username
            - name: VTT_DBPASSWORD
              valueFrom:
                secretKeyRef:
                    name:  {{ include "tech-challenge-app.fullname" . }}
                    key: db_password
            - name: VTT_DBNAME
              valueFrom:
                configMapKeyRef:
                    name:  {{ include "tech-challenge-app.fullname" . }}
                    key: db_name
            - name: VTT_DBPORT
              valueFrom:
                configMapKeyRef:
                    name:  {{ include "tech-challenge-app.fullname" . }}
                    key: db_port
            - name: VTT_DBHOST
              valueFrom:
                configMapKeyRef:
                    name:  {{ include "tech-challenge-app.fullname" . }}
                    key: db_host
            - name: VTT_LISTENHOST
              valueFrom:
                configMapKeyRef:
                    name:  {{ include "tech-challenge-app.fullname" . }}
                    key: listen_host
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
