name: 'Terraform'

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read

env:
  MODULE_PATH: infrastructure/modules
  AWS_DEFAULT_REGION: ap-southeast-2

jobs:
  validate-terraform:
    runs-on: ubuntu-latest
    environment: development

    # Use the Bash shell
    defaults:
      run:
        shell: bash

    steps:
    # Install the specific version of Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.7

    # Set AWS credentials for the CLI
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{env.AWS_DEFAULT_REGION}}

    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Initialize a new or existing Terraform working directory - state-backend
    - name: State-backend Terraform Init 
      working-directory: '${{env.MODULE_PATH}}/state-backend'
      run: terraform init

    # Checks that all Terraform configuration files adhere to a canonical format - state-backend
    - name: State-backend Terraform Format
      working-directory: '${{env.MODULE_PATH}}/state-backend'
      run: terraform fmt -check

    # Generates an execution plan for Terraform - state-backend
    - name: State-backend Terraform Plan
      working-directory: '${{env.MODULE_PATH}}/state-backend'
      run: terraform plan -input=false

    # Initialize a new or existing Terraform working directory - vpc
    - name: VPC Terraform Init 
      working-directory: '${{env.MODULE_PATH}}/vpc'
      run: terraform init

    # Checks that all Terraform configuration files adhere to a canonical format - vpc
    - name: VPC Terraform Format
      working-directory: '${{env.MODULE_PATH}}/vpc'
      run: terraform fmt -check

    # Initialize a new or existing Terraform working directory - eks
    - name: EKS Terraform Init 
      working-directory: '${{env.MODULE_PATH}}/eks'
      run: terraform init

    # Checks that all Terraform configuration files adhere to a canonical format - eks
    - name: EKS Terraform Format
      working-directory: '${{env.MODULE_PATH}}/eks'
      run: terraform fmt -check

    # Initialize a new or existing Terraform working directory - secretsmanager
    - name: Secretsmanager Terraform Init 
      working-directory: '${{env.MODULE_PATH}}/secretsmanager'
      run: terraform init

    # Checks that all Terraform configuration files adhere to a canonical format - secretsmanager
    - name: Secretsmanager Terraform Format
      working-directory: '${{env.MODULE_PATH}}/secretsmanager'
      run: terraform fmt -check
      
    # Initialize a new or existing Terraform working directory - bastion
    - name: Bastion Terraform Init 
      working-directory: '${{env.MODULE_PATH}}/bastion'
      run: terraform init

    # Checks that all Terraform configuration files adhere to a canonical format - bastion
    - name: Bastion Terraform Format
      working-directory: '${{env.MODULE_PATH}}/bastion'
      run: terraform fmt -check

    # Initialize a new or existing Terraform working directory - provisioner
    - name: Provisioner Terraform Init 
      working-directory: '${{env.MODULE_PATH}}/provisioner'
      run: terraform init

    # Checks that all Terraform configuration files adhere to a canonical format - provisioner
    - name: Provisioner Terraform Format
      working-directory: '${{env.MODULE_PATH}}/provisioner'
      run: terraform fmt -check

    # Initialize a new or existing Terraform working directory - acm
    - name: Provisioner Terraform Init 
      working-directory: '${{env.MODULE_PATH}}/acm'
      run: terraform init

    # Checks that all Terraform configuration files adhere to a canonical format - acm
    - name: Provisioner Terraform Format
      working-directory: '${{env.MODULE_PATH}}/acm'
      run: terraform fmt -check

    # Initialize a new or existing Terraform working directory - rds
    - name: RDS Terraform Init 
      working-directory: '${{env.MODULE_PATH}}/rds'
      run: terraform init

    # Checks that all Terraform configuration files adhere to a canonical format - rds
    - name: RDS Terraform Format
      working-directory: '${{env.MODULE_PATH}}/rds'
      run: terraform fmt -check
    